#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DSA_Mobile.Droid.Resource", IsApplication=true)]

namespace DSA_Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::DSA_Mobile.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::DSA_Mobile.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::DSA_Mobile.Droid.Resource.Attribute.actionBarSize;
			global::Plugin.LocalNotifications.Resource.Drawable.plugin_lc_smallicon = global::DSA_Mobile.Droid.Resource.Drawable.plugin_lc_smallicon;
			global::Plugin.Vibrate.Resource.String.ApplicationName = global::DSA_Mobile.Droid.Resource.String.ApplicationName;
			global::Plugin.Vibrate.Resource.String.Hello = global::DSA_Mobile.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int plugin_lc_smallicon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
